version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: devoure
      MONGO_INITDB_ROOT_PASSWORD: password4devoure

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devoure
      ME_CONFIG_MONGODB_ADMINPASSWORD: password4devoure
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

